### ISSUE TITLE
The plugin does not work properly

### ISSUE THREAD

**Issue by beatricelucaci** [ColorlibHQ/simple-custom-post-order#120]
I would like to report a weird issue. The plugin only works when another plugin which does the same job is installed but not activated.

We are using the Divi theme and we needed a plugin to reorder the projects and the project categories. We managed to reorder the projects but when we tried with the project categories, it woulld not save the custom order and apart from that, it made the categories on the single project pages disappear. So while we were trying other plugins, we noticed that the categories appeared once we installed the plugin “Intuitive Custom Post Order” and we hadn’t activated it yet. It’s weird but right now everything is working just because we have the plugin I mentioned… installed but not actiivated.

https://wordpress.org/support/topic/the-plugin-does-not-work-properly-6/

**Comment by TeoAlex** [comment]
The issue comes most likely from a caching system that cached the nonce we use to make our order AJAX calls. Tried using the DIVI theme's Projects CPT and successfully reordered the projects and the projects category.z

The reason it worked once they installed the plugin “Intuitive Custom Post Order” is that the cache was deleted on plugin install and the generated nonce worked for 1 hour ( or whatever the validity of the nonce is )
