### ISSUE TITLE
 Sticky posts no longer sticky when plugin is activated

### ISSUE THREAD

**Issue by mplusb** [ColorlibHQ/simple-custom-post-order#68]
https://wordpress.org/support/topic/sticky-posts-no-longer-sticky-when-plugin-is-activated/

**Comment by TeoAlex** [comment]
The issue was fixed in a previous release
![image](https://github.com/ColorlibHQ/simple-custom-post-order/assets/19348508/dbfb3e53-5282-4082-a65a-9ee3e3ff4252)
![image](https://github.com/ColorlibHQ/simple-custom-post-order/assets/19348508/3f041e31-d980-4c3c-bde6-55d14b649a2b)
Both sticky posts are at the top of the listing followed by the order set with SCPO
