### ISSUE TITLE
"get_terms" orderby in code is ignored

### ISSUE THREAD

**Issue by kuratov** [ColorlibHQ/simple-custom-post-order#88]
https://wordpress.org/support/topic/get_terms-orderby-in-code-is-ignored/

Hi.
This is great plugin for my needs. 
But I noticed one thing. With this plugin, the orderby property specified in get_terms is ignored. Maybe I didn't understand something, or maybe it's a flaw. If this is really a flaw, then I can provide a solution to this problem.

P.S. Sorry for my English)

**Comment by kuratov** [comment]
For example:
`$terms = get_terms( [
            'taxonomy' => 'custom_taxonomy',
            'hide_empty' => false,
            'orderby'  => 'slug'
        ] );`
orderby is ignored

My issue:

1) append to function scporder_get_terms_orderby
`if ($orderby !== 't.name'){
            return $orderby;
        }`

2) update `function scporder_get_object_terms($terms)` to this `function scporder_get_object_terms($terms, $taxonomy, $query_vars)`

3) prepend to function scporder_get_object_terms($terms, $taxonomy, $query_vars)
`if ($query_vars['orderby'] !== 'name'){
            return $terms;
        }`

**Comment by rolturn** [comment]
Any update on this issue? I have been waiting to see if I this will be addressed.

**Comment by chrispink** [comment]
I'm going to add to this issue because it is, currently, rendering the plugin unusable for taxonomies. 

When using `get_terms()` the order is `term_order` (and it's not possible to override, `menu_order` is not a parameter in any of the term listing functions. )

However, when the parameter `parent=>0` is set for `get_terms()` the order is as Admin

**Comment by cristiandagnino** [comment]
Any updates on this?
Thank you!

**Comment by cristiandagnino** [comment]
Meanwhile, i suggest doing it with WP_Term_Query:
```

$term_query = new WP_Term_Query( array( 
    'taxonomy' => 'regions', // <-- Custom Taxonomy name..
    'orderby'                => 'name',
    'order'                  => 'ASC',
    'child_of'               => 0,
    'parent'                 => 0,
    'fields'                 => 'all',
    'hide_empty'             => false,
) );
 
// Show Array info
echo '<pre>';
print_r( $term_query->terms );
echo '</pre>';
 
 
//Render html
if ( ! empty( $term_query->terms ) ) {
    foreach ( $term_query->terms as $term ) {
        echo wp_kses_post( $term->name ) . ", ";
        echo esc_html( $term->term_id ) . ", ";
        echo esc_html( $term->slug ) . ", ";
        echo "<br>";
    }
} else {
    echo 'No term found.';
}
```

**Comment by TeoAlex** [comment]
A simple solution to this issue is to use 'suppress_filter' arg like so:
`$terms = get_terms( [ 'taxonomy' => 'project_category', 'hide_empty' => false, 'orderby'  => 'slug', 'suppress_filter' => 'true' ] );`

The plugin is using 'get_terms' filter and there is no way to know if 'orderby' is used as a parameter to get_terms( ) function or it's the default.
